alias setup-terminal=". $DOT_FILES/scripts/terminal.sh"
alias setup-homebrew=". $DOT_FILES/scripts/homebrew.sh"
alias setup-binaries=". $DOT_FILES/scripts/binaries.sh"
alias setup-apps=". $DOT_FILES/scripts/apps.sh"
alias setup-system=". $DOT_FILES/scripts/system.sh"
alias setup-custom=". $DOT_FILES/scripts/custom.sh"
