return {
  {
    "stevearc/conform.nvim",
    event = "BufWritePre",
    opts = {
      formatters_by_ft = {
        astro = { "prettierd", "prettier" },
        bash = { "shfmt" },
        cs = { "csharpier" },
        css = { "prettierd", "prettier", "stylelint" },
        elixir = { "mix_format" },
        fsharp = { "fantomas" },
        go = { "gofumpt", "goimports" },
        haskell = { "ormolu" },
        html = { "prettierd", "prettier" },
        java = { "google-java-format" },
        javascript = { "prettierd", "prettier" },
        json = { "prettierd", "prettier", "jq" },
        kotlin = { "ktlint" },
        lua = { "stylua" },
        markdown = { "prettierd", "prettier" },
        perl = { "perltidy" },
        php = { "php_cs_fixer" },
        python = { "black" },
        ruby = { "rubocop" },
        rust = { "rustfmt" },
        scala = { "scalafmt" },
        sql = { "sqlfluff", "sqlfmt" },
        swift = { "swiftformat" },
        toml = { "taplo" },
        typescript = { "prettierd", "prettier" },
        vue = { "prettierd", "prettier" },
        xml = { "xmllint" },
        yaml = { "prettierd", "prettier" },
        zig = { "zigfmt" },
      },
    },
  },
}
