return {
  {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    opts = {
      ensure_installed = {
        -- general
        "astro",
        "bash",
        "c",
        "c_sharp",
        "cpp",
        "css",
        "elixir",
        "fortran",
        "fsharp",
        "go",
        "haskell",
        "html",
        "java",
        "javascript",
        "json",
        "kotlin",
        "lua",
        "markdown",
        "objc",
        "objcpp",
        "perl",
        "php",
        "python",
        "ruby",
        "rust",
        "scala",
        "sql",
        "swift",
        "toml",
        "tsx",
        "typescript",
        "vue",
        "xml",
        "yaml",
        "zig",

        -- misc
        "dockerfile",
        "gitignore",
        "graphql",
        "ini",
        "make",
        "markdown_inline",
        "proto",
        "query",
        "regex",
        "scss",
        "vim",
        "vimdoc",
      },

      highlight = { enable = true },
      indent = { enable = true },
      incremental_selection = {
        enable = true,
        keymaps = {
          init_selection = "gnn",
          node_incremental = "grn",
          scope_incremental = "grc",
          node_decremental = "grm",
        },
      },
    },
  },
}
